### ISSUE TITLE
Unable to find "IfBody" method on ApiStub object

### ISSUE THREAD

**Issue by Dileep17** [markvincze/Stubbery#12]
Hi!

In [doc of the stubbery](https://github.com/markvincze/Stubbery/blob/ab22f439b540db7d68ba00fd26e1dc3e60cdba08/docs/documentation/preconditions.md), I found below. A way to return response based on the body posted.  

> `// Will only respond if the body contains the string "bodyCondition".
> sut.Post("/testget", (req, args) => "testresponse")
>     .IfBody(s => s.ReadAsString().Contains("bodyCondition"));`

There seems to be no `IfBody` method on ApiStub() object.

 Is this replaced with any new method ? Please correct me if Im doing something wrong here! 

Thank you in advance.

**Comment by markvincze** [comment]
Hi @Dileep17,

That feature was removed due to causing some problems, but the documentation wasn't adjusted. I fixed the docs now, and will try to investigate how we can reintroduce this feature.

Cheers,
Mark

**Comment by markvincze** [comment]
Feature was added in #14
