### ISSUE TITLE
How to dynamically change the response Status Code?

### ISSUE THREAD

**Issue by dstj** [markvincze/Stubbery#23]
Hi,

I'd like to make it a feature request. It would be nice to be able to dynamically change the response status code based on some class property. For example, something like:

```
public bool MockBadSecurityRights { get; set; }

_stub.Request(HttpMethod.Patch)
		.IfRoute("/some-resource/{id}")
		.Response((req, args) => {
			return !MockBadSecurityRights ? "OK" : "ERROR;
		})
		.StatusCode(() => {
			return !MockBadSecurityRights ? 200 : 403;
		})
	;
```
The same would go for headers. This would be very helpful to test error scenarios without having to mock a route just for that error case.

**Comment by markvincze** [comment]
Thanks for the request! I added this feature in 2.4.0.
