### ISSUE TITLE
Request Matching as a separate library

### ISSUE THREAD

**Issue by urdeveloper** [markvincze/Stubbery#8]
Hi Mark,
I came across your code and found the request matching part very interesting and useful. Good job man! 
I was wondering if there's any plan to make the request matching code a separate library/package?

**Comment by markvincze** [comment]
Hi @urdeveloper,

Thanks, I'm glad you found it interesting!  
No, I didn't have any plans to extract it, but it's certainly an option.  
If you're interested, I documented some more details about specifically the route matching [here](https://blog.markvincze.com/matching-route-templates-manually-in-asp-net-core/).

**Comment by urdeveloper** [comment]
Thanks for the information!
